//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEmployers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int Номер { get; set; }
        public string Название_товара { get; set; }
        public int Сотрудник_ID { get; set; }
    
        public virtual EmployersTable Employers { get; set; }
    }
}
