//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEmployers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTable
    {
        public int Товар_ID { get; set; }
        public string Название_товара { get; set; }

        public override string ToString()
        {
            return Название_товара;
        }
    }
}
